# Generated by Django 5.2.17 on 2026-09-12 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='processingjob',
            new_name='core_proces_session_e60025_idx',
            old_name='core_proces_session_8e9d6e_idx',
        ),
    ]
